blueprint:
  name: Crestron Dimmer/Keypad Button Controller
  description: >
    Configure actions for Crestron dimmer/keypad button presses (single, double, hold)
    and optionally set LED binding for visual feedback.

    **Simple Setup:** Just select your dimmer device once. Button events and LED switches are discovered automatically.
    Configure actions and LED bindings only for the buttons you want to use.
  domain: automation
  author: adamjs83
  source_url: https://github.com/adamjs83/creston-xsig-hassio/blob/main/blueprints/automation/crestron_dimmer_button_controller.yaml

  input:
    dimmer_device:
      name: Dimmer/Keypad Device
      description: Select your Crestron dimmer/keypad device (used for LED switch auto-discovery)
      selector:
        device:
          integration: crestron

    # ========== Button 1 ==========
    button_1_event:
      name: "Button 1 Event Entity (Optional)"
      description: Select the button 1 event entity (e.g., event.dimmer_name_button_1)
      default: ""
      selector:
        entity:
          filter:
            - domain: event

    button_1_press:
      name: "Button 1 - Press Action (Optional)"
      description: Action to run when button 1 is pressed once
      default: []
      selector:
        action: {}

    button_1_double:
      name: "Button 1 - Double Press Action (Optional)"
      description: Action to run when button 1 is double pressed
      default: []
      selector:
        action: {}

    button_1_hold:
      name: "Button 1 - Hold Action (Optional)"
      description: Action to run when button 1 is held
      default: []
      selector:
        action: {}

    button_1_led_entity:
      name: "Button 1 - LED Binding (Optional)"
      description: Bind button 1 LED to an entity for automatic feedback (light, switch, etc.)
      default: ""
      selector:
        entity: {}

    # ========== Button 2 ==========
    button_2_event:
      name: "Button 2 Event Entity (Optional)"
      description: Select the button 2 event entity
      default: ""
      selector:
        entity:
          filter:
            - domain: event

    button_2_press:
      name: "Button 2 - Press Action (Optional)"
      description: Action to run when button 2 is pressed once
      default: []
      selector:
        action: {}

    button_2_double:
      name: "Button 2 - Double Press Action (Optional)"
      description: Action to run when button 2 is double pressed
      default: []
      selector:
        action: {}

    button_2_hold:
      name: "Button 2 - Hold Action (Optional)"
      description: Action to run when button 2 is held
      default: []
      selector:
        action: {}

    button_2_led_entity:
      name: "Button 2 - LED Binding (Optional)"
      description: Bind button 2 LED to an entity for automatic feedback
      default: ""
      selector:
        entity: {}

    # ========== Button 3 ==========
    button_3_event:
      name: "Button 3 Event Entity (Optional)"
      description: Select the button 3 event entity
      default: ""
      selector:
        entity:
          filter:
            - domain: event

    button_3_press:
      name: "Button 3 - Press Action (Optional)"
      description: Action to run when button 3 is pressed once
      default: []
      selector:
        action: {}

    button_3_double:
      name: "Button 3 - Double Press Action (Optional)"
      description: Action to run when button 3 is double pressed
      default: []
      selector:
        action: {}

    button_3_hold:
      name: "Button 3 - Hold Action (Optional)"
      description: Action to run when button 3 is held
      default: []
      selector:
        action: {}

    button_3_led_entity:
      name: "Button 3 - LED Binding (Optional)"
      description: Bind button 3 LED to an entity for automatic feedback
      default: ""
      selector:
        entity: {}

    # ========== Button 4 ==========
    button_4_event:
      name: "Button 4 Event Entity (Optional)"
      description: Select the button 4 event entity
      default: ""
      selector:
        entity:
          filter:
            - domain: event

    button_4_press:
      name: "Button 4 - Press Action (Optional)"
      description: Action to run when button 4 is pressed once
      default: []
      selector:
        action: {}

    button_4_double:
      name: "Button 4 - Double Press Action (Optional)"
      description: Action to run when button 4 is double pressed
      default: []
      selector:
        action: {}

    button_4_hold:
      name: "Button 4 - Hold Action (Optional)"
      description: Action to run when button 4 is held
      default: []
      selector:
        action: {}

    button_4_led_entity:
      name: "Button 4 - LED Binding (Optional)"
      description: Bind button 4 LED to an entity for automatic feedback
      default: ""
      selector:
        entity: {}

    # ========== Button 5 ==========
    button_5_event:
      name: "Button 5 Event Entity (Optional)"
      description: Select the button 5 event entity
      default: ""
      selector:
        entity:
          filter:
            - domain: event

    button_5_press:
      name: "Button 5 - Press Action (Optional)"
      description: Action to run when button 5 is pressed once
      default: []
      selector:
        action: {}

    button_5_double:
      name: "Button 5 - Double Press Action (Optional)"
      description: Action to run when button 5 is double pressed
      default: []
      selector:
        action: {}

    button_5_hold:
      name: "Button 5 - Hold Action (Optional)"
      description: Action to run when button 5 is held
      default: []
      selector:
        action: {}

    button_5_led_entity:
      name: "Button 5 - LED Binding (Optional)"
      description: Bind button 5 LED to an entity for automatic feedback
      default: ""
      selector:
        entity: {}

    # ========== Button 6 ==========
    button_6_event:
      name: "Button 6 Event Entity (Optional)"
      description: Select the button 6 event entity
      default: ""
      selector:
        entity:
          filter:
            - domain: event

    button_6_press:
      name: "Button 6 - Press Action (Optional)"
      description: Action to run when button 6 is pressed once
      default: []
      selector:
        action: {}

    button_6_double:
      name: "Button 6 - Double Press Action (Optional)"
      description: Action to run when button 6 is double pressed
      default: []
      selector:
        action: {}

    button_6_hold:
      name: "Button 6 - Hold Action (Optional)"
      description: Action to run when button 6 is held
      default: []
      selector:
        action: {}

    button_6_led_entity:
      name: "Button 6 - LED Binding (Optional)"
      description: Bind button 6 LED to an entity for automatic feedback
      default: ""
      selector:
        entity: {}

mode: parallel
max: 10

variables:
  dimmer_device: !input dimmer_device
  # Auto-discover LED switch entities from the dimmer device
  led_switches: "{{ device_entities(dimmer_device) | select('match', '^switch\\..*_led_[1-6]$') | list | sort }}"
  led_1: "{{ led_switches | select('match', '.*_led_1$') | first | default('') }}"
  led_2: "{{ led_switches | select('match', '.*_led_2$') | first | default('') }}"
  led_3: "{{ led_switches | select('match', '.*_led_3$') | first | default('') }}"
  led_4: "{{ led_switches | select('match', '.*_led_4$') | first | default('') }}"
  led_5: "{{ led_switches | select('match', '.*_led_5$') | first | default('') }}"
  led_6: "{{ led_switches | select('match', '.*_led_6$') | first | default('') }}"
  # User-configured LED binding entities
  button_1_led: !input button_1_led_entity
  button_2_led: !input button_2_led_entity
  button_3_led: !input button_3_led_entity
  button_4_led: !input button_4_led_entity
  button_5_led: !input button_5_led_entity
  button_6_led: !input button_6_led_entity

trigger:
  # Button Event Triggers (filtered to device entities)
  - platform: state
    entity_id: !input button_1_event
    id: button_1

  - platform: state
    entity_id: !input button_2_event
    id: button_2

  - platform: state
    entity_id: !input button_3_event
    id: button_3

  - platform: state
    entity_id: !input button_4_event
    id: button_4

  - platform: state
    entity_id: !input button_5_event
    id: button_5

  - platform: state
    entity_id: !input button_6_event
    id: button_6

  # LED Binding State Triggers (v1.20.8+)
  # Sync LED switches when bound entity states change
  - platform: state
    entity_id: !input button_1_led_entity
    id: led_1_sync

  - platform: state
    entity_id: !input button_2_led_entity
    id: led_2_sync

  - platform: state
    entity_id: !input button_3_led_entity
    id: led_3_sync

  - platform: state
    entity_id: !input button_4_led_entity
    id: led_4_sync

  - platform: state
    entity_id: !input button_5_led_entity
    id: led_5_sync

  - platform: state
    entity_id: !input button_6_led_entity
    id: led_6_sync

action:
  - variables:
      event_type: "{{ trigger.to_state.attributes.event_type }}"

  - choose:
      # ========== Button 1 ==========
      - conditions:
          - condition: trigger
            id: button_1
          - "{{ event_type == 'press' }}"
        sequence: !input button_1_press

      - conditions:
          - condition: trigger
            id: button_1
          - "{{ event_type == 'double_press' }}"
        sequence: !input button_1_double

      - conditions:
          - condition: trigger
            id: button_1
          - "{{ event_type == 'hold' }}"
        sequence: !input button_1_hold

      # ========== Button 2 ==========
      - conditions:
          - condition: trigger
            id: button_2
          - "{{ event_type == 'press' }}"
        sequence: !input button_2_press

      - conditions:
          - condition: trigger
            id: button_2
          - "{{ event_type == 'double_press' }}"
        sequence: !input button_2_double

      - conditions:
          - condition: trigger
            id: button_2
          - "{{ event_type == 'hold' }}"
        sequence: !input button_2_hold

      # ========== Button 3 ==========
      - conditions:
          - condition: trigger
            id: button_3
          - "{{ event_type == 'press' }}"
        sequence: !input button_3_press

      - conditions:
          - condition: trigger
            id: button_3
          - "{{ event_type == 'double_press' }}"
        sequence: !input button_3_double

      - conditions:
          - condition: trigger
            id: button_3
          - "{{ event_type == 'hold' }}"
        sequence: !input button_3_hold

      # ========== Button 4 ==========
      - conditions:
          - condition: trigger
            id: button_4
          - "{{ event_type == 'press' }}"
        sequence: !input button_4_press

      - conditions:
          - condition: trigger
            id: button_4
          - "{{ event_type == 'double_press' }}"
        sequence: !input button_4_double

      - conditions:
          - condition: trigger
            id: button_4
          - "{{ event_type == 'hold' }}"
        sequence: !input button_4_hold

      # ========== Button 5 ==========
      - conditions:
          - condition: trigger
            id: button_5
          - "{{ event_type == 'press' }}"
        sequence: !input button_5_press

      - conditions:
          - condition: trigger
            id: button_5
          - "{{ event_type == 'double_press' }}"
        sequence: !input button_5_double

      - conditions:
          - condition: trigger
            id: button_5
          - "{{ event_type == 'hold' }}"
        sequence: !input button_5_hold

      # ========== Button 6 ==========
      - conditions:
          - condition: trigger
            id: button_6
          - "{{ event_type == 'press' }}"
        sequence: !input button_6_press

      - conditions:
          - condition: trigger
            id: button_6
          - "{{ event_type == 'double_press' }}"
        sequence: !input button_6_double

      - conditions:
          - condition: trigger
            id: button_6
          - "{{ event_type == 'hold' }}"
        sequence: !input button_6_hold

  # LED State Sync (v1.20.8+)
  # Directly control LED switches based on bound entity states
  - choose:
      # Button 1 LED Sync
      - conditions:
          - condition: trigger
            id: led_1_sync
          - "{{ button_1_led != '' and led_1 != '' }}"
        sequence:
          - service: "switch.turn_{{ 'on' if trigger.to_state.state in ['on', 'home', 'playing', 'open', 'locked', 'cleaning', 'heat', 'cool', 'auto', 'heat_cool', 'armed_away', 'armed_home', 'armed_night', 'above_horizon'] else 'off' }}"
            target:
              entity_id: "{{ led_1 }}"

      # Button 2 LED Sync
      - conditions:
          - condition: trigger
            id: led_2_sync
          - "{{ button_2_led != '' and led_2 != '' }}"
        sequence:
          - service: "switch.turn_{{ 'on' if trigger.to_state.state in ['on', 'home', 'playing', 'open', 'locked', 'cleaning', 'heat', 'cool', 'auto', 'heat_cool', 'armed_away', 'armed_home', 'armed_night', 'above_horizon'] else 'off' }}"
            target:
              entity_id: "{{ led_2 }}"

      # Button 3 LED Sync
      - conditions:
          - condition: trigger
            id: led_3_sync
          - "{{ button_3_led != '' and led_3 != '' }}"
        sequence:
          - service: "switch.turn_{{ 'on' if trigger.to_state.state in ['on', 'home', 'playing', 'open', 'locked', 'cleaning', 'heat', 'cool', 'auto', 'heat_cool', 'armed_away', 'armed_home', 'armed_night', 'above_horizon'] else 'off' }}"
            target:
              entity_id: "{{ led_3 }}"

      # Button 4 LED Sync
      - conditions:
          - condition: trigger
            id: led_4_sync
          - "{{ button_4_led != '' and led_4 != '' }}"
        sequence:
          - service: "switch.turn_{{ 'on' if trigger.to_state.state in ['on', 'home', 'playing', 'open', 'locked', 'cleaning', 'heat', 'cool', 'auto', 'heat_cool', 'armed_away', 'armed_home', 'armed_night', 'above_horizon'] else 'off' }}"
            target:
              entity_id: "{{ led_4 }}"

      # Button 5 LED Sync
      - conditions:
          - condition: trigger
            id: led_5_sync
          - "{{ button_5_led != '' and led_5 != '' }}"
        sequence:
          - service: "switch.turn_{{ 'on' if trigger.to_state.state in ['on', 'home', 'playing', 'open', 'locked', 'cleaning', 'heat', 'cool', 'auto', 'heat_cool', 'armed_away', 'armed_home', 'armed_night', 'above_horizon'] else 'off' }}"
            target:
              entity_id: "{{ led_5 }}"

      # Button 6 LED Sync
      - conditions:
          - condition: trigger
            id: led_6_sync
          - "{{ button_6_led != '' and led_6 != '' }}"
        sequence:
          - service: "switch.turn_{{ 'on' if trigger.to_state.state in ['on', 'home', 'playing', 'open', 'locked', 'cleaning', 'heat', 'cool', 'auto', 'heat_cool', 'armed_away', 'armed_home', 'armed_night', 'above_horizon'] else 'off' }}"
            target:
              entity_id: "{{ led_6 }}"
    default: []
