blueprint:
  name: Crestron Dimmer/Keypad Button Controller
  description: >
    Configure actions for Crestron dimmer/keypad button presses.

    **Features:**
    - Supports single press, double press, and hold actions
    - Configure only the buttons you need (all others ignored)
    - All button events from the selected device are monitored

    **LED Bindings:** Configure LED bindings via the Crestron integration
    config (Settings → Devices & Services → Crestron → Configure → LED Bindings)

  domain: automation
  author: adamjs83
  source_url: https://github.com/adamjs83/creston-xsig-hassio/blob/main/blueprints/automation/crestron_dimmer_button_controller.yaml

  input:
    dimmer_device:
      name: Dimmer/Keypad Device
      description: Select your Crestron dimmer/keypad device
      selector:
        device:
          filter:
            - integration: crestron
              manufacturer: Crestron
              model: Keypad/Dimmer

    # ========== Button 1 Actions ==========
    button_1_press:
      name: "Button 1 - Press Action"
      description: Action to run when button 1 is pressed once (leave empty to ignore)
      default: []
      selector:
        action: {}

    button_1_double:
      name: "Button 1 - Double Press Action"
      description: Action to run when button 1 is double pressed (leave empty to ignore)
      default: []
      selector:
        action: {}

    button_1_hold:
      name: "Button 1 - Hold Action"
      description: Action to run when button 1 is held (leave empty to ignore)
      default: []
      selector:
        action: {}

    # ========== Button 2 Actions ==========
    button_2_press:
      name: "Button 2 - Press Action"
      description: Action to run when button 2 is pressed once (leave empty to ignore)
      default: []
      selector:
        action: {}

    button_2_double:
      name: "Button 2 - Double Press Action"
      description: Action to run when button 2 is double pressed (leave empty to ignore)
      default: []
      selector:
        action: {}

    button_2_hold:
      name: "Button 2 - Hold Action"
      description: Action to run when button 2 is held (leave empty to ignore)
      default: []
      selector:
        action: {}

    # ========== Button 3 Actions ==========
    button_3_press:
      name: "Button 3 - Press Action"
      description: Action to run when button 3 is pressed once (leave empty to ignore)
      default: []
      selector:
        action: {}

    button_3_double:
      name: "Button 3 - Double Press Action"
      description: Action to run when button 3 is double pressed (leave empty to ignore)
      default: []
      selector:
        action: {}

    button_3_hold:
      name: "Button 3 - Hold Action"
      description: Action to run when button 3 is held (leave empty to ignore)
      default: []
      selector:
        action: {}

    # ========== Button 4 Actions ==========
    button_4_press:
      name: "Button 4 - Press Action"
      description: Action to run when button 4 is pressed once (leave empty to ignore)
      default: []
      selector:
        action: {}

    button_4_double:
      name: "Button 4 - Double Press Action"
      description: Action to run when button 4 is double pressed (leave empty to ignore)
      default: []
      selector:
        action: {}

    button_4_hold:
      name: "Button 4 - Hold Action"
      description: Action to run when button 4 is held (leave empty to ignore)
      default: []
      selector:
        action: {}

    # ========== Button 5 Actions ==========
    button_5_press:
      name: "Button 5 - Press Action"
      description: Action to run when button 5 is pressed once (leave empty to ignore)
      default: []
      selector:
        action: {}

    button_5_double:
      name: "Button 5 - Double Press Action"
      description: Action to run when button 5 is double pressed (leave empty to ignore)
      default: []
      selector:
        action: {}

    button_5_hold:
      name: "Button 5 - Hold Action"
      description: Action to run when button 5 is held (leave empty to ignore)
      default: []
      selector:
        action: {}

    # ========== Button 6 Actions ==========
    button_6_press:
      name: "Button 6 - Press Action"
      description: Action to run when button 6 is pressed once (leave empty to ignore)
      default: []
      selector:
        action: {}

    button_6_double:
      name: "Button 6 - Double Press Action"
      description: Action to run when button 6 is double pressed (leave empty to ignore)
      default: []
      selector:
        action: {}

    button_6_hold:
      name: "Button 6 - Hold Action"
      description: Action to run when button 6 is held (leave empty to ignore)
      default: []
      selector:
        action: {}

mode: parallel
max: 10

variables:
  dimmer_device: !input dimmer_device
  # Auto-discover all button event entities from the selected device
  button_events: "{{ device_entities(dimmer_device) | select('match', '^event\\..*_button_[1-6]$') | list }}"

trigger:
  # Trigger on ANY button event from the selected dimmer device
  - platform: event
    event_type: crestron_button
    event_data:
      device_name: "{{ device_attr(dimmer_device, 'name') }}"

action:
  - variables:
      event_type: "{{ trigger.event.data.action }}"
      button_num: "{{ trigger.event.data.button | int }}"

  - choose:
      # ========== Button 1 Actions ==========
      - conditions:
          - "{{ button_num == 1 and event_type == 'press' }}"
        sequence: !input button_1_press

      - conditions:
          - "{{ button_num == 1 and event_type == 'double_press' }}"
        sequence: !input button_1_double

      - conditions:
          - "{{ button_num == 1 and event_type == 'hold' }}"
        sequence: !input button_1_hold

      # ========== Button 2 Actions ==========
      - conditions:
          - "{{ button_num == 2 and event_type == 'press' }}"
        sequence: !input button_2_press

      - conditions:
          - "{{ button_num == 2 and event_type == 'double_press' }}"
        sequence: !input button_2_double

      - conditions:
          - "{{ button_num == 2 and event_type == 'hold' }}"
        sequence: !input button_2_hold

      # ========== Button 3 Actions ==========
      - conditions:
          - "{{ button_num == 3 and event_type == 'press' }}"
        sequence: !input button_3_press

      - conditions:
          - "{{ button_num == 3 and event_type == 'double_press' }}"
        sequence: !input button_3_double

      - conditions:
          - "{{ button_num == 3 and event_type == 'hold' }}"
        sequence: !input button_3_hold

      # ========== Button 4 Actions ==========
      - conditions:
          - "{{ button_num == 4 and event_type == 'press' }}"
        sequence: !input button_4_press

      - conditions:
          - "{{ button_num == 4 and event_type == 'double_press' }}"
        sequence: !input button_4_double

      - conditions:
          - "{{ button_num == 4 and event_type == 'hold' }}"
        sequence: !input button_4_hold

      # ========== Button 5 Actions ==========
      - conditions:
          - "{{ button_num == 5 and event_type == 'press' }}"
        sequence: !input button_5_press

      - conditions:
          - "{{ button_num == 5 and event_type == 'double_press' }}"
        sequence: !input button_5_double

      - conditions:
          - "{{ button_num == 5 and event_type == 'hold' }}"
        sequence: !input button_5_hold

      # ========== Button 6 Actions ==========
      - conditions:
          - "{{ button_num == 6 and event_type == 'press' }}"
        sequence: !input button_6_press

      - conditions:
          - "{{ button_num == 6 and event_type == 'double_press' }}"
        sequence: !input button_6_double

      - conditions:
          - "{{ button_num == 6 and event_type == 'hold' }}"
        sequence: !input button_6_hold
    default: []
