HUB = "hub"
DOMAIN = "crestron"
CONF_PORT = "port"
CONF_TO_HUB = "to_joins"
CONF_FROM_HUB = "from_joins"
CONF_JOIN = "join"
CONF_SCRIPT = "script"
CONF_IS_ON_JOIN = "is_on_join"
CONF_HEAT_SP_JOIN = "heat_sp_join"
CONF_COOL_SP_JOIN = "cool_sp_join"
CONF_REG_TEMP_JOIN = "reg_temp_join"
CONF_MODE_HEAT_JOIN = "mode_heat_join"
CONF_MODE_COOL_JOIN = "mode_cool_join"
CONF_MODE_AUTO_JOIN = "mode_auto_join"
CONF_MODE_OFF_JOIN = "mode_off_join"
CONF_FAN_ON_JOIN = "fan_on_join"
CONF_FAN_AUTO_JOIN = "fan_auto_join"
CONF_H1_JOIN = "h1_join"
CONF_H2_JOIN = "h2_join"
CONF_C1_JOIN = "c1_join"
CONF_C2_JOIN = "c2_join"
CONF_FA_JOIN = "fa_join"
CONF_IS_OPENING_JOIN = "is_opening_join"
CONF_IS_CLOSING_JOIN = "is_closing_join"
CONF_IS_CLOSED_JOIN = "is_closed_join"
CONF_STOP_JOIN = "stop_join"
CONF_POS_JOIN = "pos_join"
CONF_BRIGHTNESS_JOIN = "brightness_join"
CONF_MUTE_JOIN = "mute_join"
CONF_VOLUME_JOIN = "volume_join"
CONF_SOURCE_NUM_JOIN = "source_number_join"
CONF_SOURCES = "sources"
CONF_VALUE_JOIN = "value_join"
CONF_DIVISOR = "divisor"
CONF_SWITCH_JOIN = "switch_join"

# Climate additional constants
CONF_MODE_HEAT_COOL_JOIN = "mode_heat_cool_join"
CONF_FAN_MODE_AUTO_JOIN = "fan_mode_auto_join"
CONF_FAN_MODE_ON_JOIN = "fan_mode_on_join"
CONF_HVAC_ACTION_HEAT_JOIN = "hvac_action_heat_join"
CONF_HVAC_ACTION_COOL_JOIN = "hvac_action_cool_join"
CONF_HVAC_ACTION_IDLE_JOIN = "hvac_action_idle_join"

# Floor warming thermostat constants (new)
CONF_FLOOR_MODE_JOIN = "floor_mode_join"           # analog set: 1=Off, 2=Heat
CONF_FLOOR_MODE_FB_JOIN = "floor_mode_fb_join"     # analog feedback: 1/2
CONF_FLOOR_SP_JOIN = "floor_sp_join"               # analog setpoint (tenths)
CONF_FLOOR_SP_FB_JOIN = "floor_sp_fb_join"         # analog setpoint feedback (tenths)
CONF_FLOOR_TEMP_JOIN = "floor_temp_join"           # analog floor temperature (tenths)
